### ISSUE TITLE
Stale files might end up in Lambda ZIP file

### ISSUE THREAD

**Issue by szilveszter** [racker/fleece#74]
In a local development environment, where I tend to run `fleece build` very frequently to test out things in a remote development environment, I noticed that the Lambda ZIP file might end up containing files that I have since removed from the source directory. This might have unexpected consequences (e.g. when you create a sub-module from a file). I could temporarily work around the problem by removing the local volumes the build command created, but it might be worth having this as part of the build process itself. I assume the original goal was to preserve the build cache, which would still be useful, but all other volumes should be destroyed before a new build to achieve a full clean build.

**Comment by miguelgrinberg** [comment]
@szilveszter hey, just to make sure I understand what you are asking, what files get in your lambda zip packages? Files that you deleted but remain in a copy of the zip file that was left in the docker volume? I can delete the old volume before start a build, that actually seems like a good idea always, so that you end up with more deterministic builds.

The `--rebuild` option takes care of the cache, so I think we are good on forcing an update when dependencies change, correct?
